config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'tasks#index'
  resources :tasks do
    member do
      get 'complete'
    end
  end
  get 'not_authentificated', to: 'tasks#not_authentificated'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :parent, class_name: 'User', optional: true

  delegate :full_name, to: :parent, prefix: true

  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }

  STATUSES = [
    NEW = 'new',
    IN_PROGRESS = 'in progress',
    DONE = 'done'
  ]

  def complete!
    update_column(:status, Task::DONE)
  end

  def task_done?
    status == Task::DONE
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy

  validates :first_name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 50 }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index not_authentificated]

  before_action :set_task, only: %i[show edit update destroy complete]
  before_action :check_user_tasks, only: %i[show edit update destroy]

  def index
    return redirect_to not_authentificated_path unless user_signed_in?

    @tasks = current_user.tasks.where.not(status: Task::DONE).order(updated_at: :desc)

    @completed_tasks = current_user.tasks.where(status: Task::DONE).order(updated_at: :desc)
  end

  def not_authentificated; end

  def new
    @task = Task.new

    @users_for_select = emails_and_users_id
  end

  def show; end

  def create
    @task = assigned_task? ? Task.create(assigned_task_params) : current_user.tasks.create(task_params)

    if @task.errors.empty?
      redirect_to tasks_path
    else
      @users_for_select = emails_and_users_id
      render :edit
    end
  end

  def edit
    @users_for_select = emails_and_users_id
  end

  def update
    updated_task = assigned_task? ? assigned_task_params : task_params

    if @task.update updated_task
      flash[:notice] = 'Task was updated successfully'
      redirect_to tasks_path
    else
      @users_for_select = emails_and_users_id
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    flash[:alert] = 'Task was deleted successfully'
    redirect_to tasks_path
  end

  def complete
    @task.complete!

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :status)
  end

  def assigned_task_params
    user_id = params[:task][:parent_id]
    parent_id = current_user.id
    task_params.merge(user_id: user_id, parent_id: parent_id)
  end

  def assigned_task?
    params[:task][:assigned_task].to_i == 1
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def check_user_tasks
    return unless current_user != @task.user

    flash[:alert] = 'You can only edit, view, delete your own task'
    redirect_to tasks_path
  end

  def emails_and_users_id
    User.where.not(email: current_user.email).pluck(:email, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def status_color(status)
    {
      new: 'danger',
      in_progress: 'warning',
      done: 'success'
    }[status.to_sym]
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <i class="fas fa-clipboard-list"></i>
    To-do list
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= link_to root_path, class: "nav-link #{'active font-weight-bold' if current_page?(root_path)}" do %>
        <div class="fa fa-home"></div>
        Home
      <% end %>
    </ul>
    <ul class="navbar-nav mr-right">
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="fa fa-user"></div>
            <b><%= current_user.email %></b>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to edit_user_registration_path, class: "dropdown-item #{'active font-weight-bold' if current_page?(edit_user_registration_path)}" do %>
              <div class="fa fa-cog"></div>
              <b>Account settings</b>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              <div class="fa fa-sign-out-alt"></div>
              <b>Sign out</b>
            <% end %>
          </div>
        </li>
      <% else %>
        <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active font-weight-bold' if current_page?(new_user_session_path)}" %>
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active font-weight-bold' if current_page?(new_user_registration_path)}" %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= render 'errors', obj: @task %>

<%= form_with model: @task do |f| %>
  <div class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <% if @task.id.present? %>
    <div class="form-group">
      <%= f.select :status, Task::STATUSES %>
    </div>
  <% end %>


  <% unless @users_for_select.empty? %>
    <% if @task.parent_id.nil? %>
      <div class="form-group">
        <%= f.label :assigned_task %>
        <%= f.check_box :assigned_task, id: 'assigned_checkbox' %>
      </div>

      <div class="form-group" id="assigned_select">
        <%= f.label :parent_id, 'Assign to:' %>
        <%= f.select :parent_id, @users_for_select, class: 'form-control' %>
      </div>
    <% else %>
      <div class="form-group">
        <p> The task is assigned by <%= @task.parent_full_name %>
      </div>
    <% end %>
  <% end %>

  <%= f.submit class: 'btn btn-primary'%>
<% end %>

app/views/tasks/_task.html.erb
<div class="container border bg-light">
  <div class="row">
    <div class="col-sm text-<%= status_color(task.status) %>">
      <%= link_to_unless_current task.title, task, class: "a-status-#{task.status == 'in progress' ? 'in-progress' : task.status}" %>
    </div>
    <div class="col-sm text-<%= status_color(task.status) %>">
      <%= truncate(task.description) %>
    </div>
    <div class="col-sm text-<%= status_color(task.status) %>">
      <%= task.status %>
      <%= link_to content_tag('i', '', class: 'fas fa-pencil-alt'), edit_task_path(task), class: 'action ml-4'%>
      <%= link_to content_tag('i', '', class: 'fas fa-trash-alt'), task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'action'%>
      <%= unless task.task_done?
            link_to content_tag('i', '', class: 'fas fa-check-square'), complete_task_path(task), class: 'action'
          end
      %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Task edit</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<% unless @tasks.empty? %>
  <div class="container">

      <div class="row">
        <div class="col">
          <h3 class="text-center">Task</h3>
        </div>
      </div>
      <div class="container border bg-light">
        <div class="row">
          <div class="col-sm">
            Title
          </div>
          <div class="col-sm">
            Description
          </div>
          <div class="col-sm">
            Status
          </div>
        </div>
      </div>

      <% @tasks.each do |task| %>
        <%= render partial: 'task', object: task%>
      <% end%>

    <%= link_to 'Create task', new_task_path, class: 'btn btn-primary mt-1'%>
  </div>
<% else %>
  <div class="container bg-light">
    <div class="row">
      <div class="col-sm text-center">
        <h3>No task</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-sm text-center">
        <%= link_to 'Create task', new_task_path, class: 'btn btn-primary mt-1'%>
      </div>
    </div>
  </div>
<% end%>

<% unless @completed_tasks.empty? %>
  <div class="container">
    <div class="row">
      <div class="col">
        <h3 class="text-center">Task done</h3>
      </div>
    </div>

    <% @completed_tasks.each do |task| %>
      <%= render partial: 'task', object: task%>
    <% end %>

  </div>
<% end %>

app/views/tasks/new.html.erb
<h1>Create task</h1>
<%= render 'form' %>

app/views/tasks/no_authenticate.html.erb
<div class="container bg-light p-3 border border-dark rounded">
  <h1 class="text-center">Sign up to create your task list</h1>

  <div class="d-flex justify-content-center">
    <%= link_to 'Sign up', new_user_session_path, class: 'btn btn-primary px-5 py-1 mt-4' %>
  </div>
</div>

app/views/tasks/no_authenticate_index.html.erb
<div class="container bg-light p-3 border border-dark rounded">
  <h1 class="text-center">Sign up to create your task list</h1>

  <div class="d-flex justify-content-center">
    <%= link_to 'Sign up', new_user_session_path, class: 'btn btn-primary px-5 py-1 mt-4' %>
  </div>
</div>

app/views/tasks/not_authentificated.html.erb
<div class="container bg-light p-3 border border-dark rounded">
  <h1 class="text-center">Sign up to create your task list</h1>

  <div class="d-flex justify-content-center">
    <%= link_to 'Sign up', new_user_session_path, class: 'btn btn-primary px-5 py-1 mt-4' %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="card bg-light">
  <div class="card-body">
    <h5 class="card-title"><%= @task.title %></h5>
    <p class="card-text"><%= @task.description %></p>
    <%= link_to 'Edit card', edit_task_path, class: 'card-link' %>
    <%= link_to 'Back to all tasks', tasks_path, class: 'card-link' %>
  </div>
</div>